# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xpcs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1553, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.file_panel = QtWidgets.QFrame(self.centralwidget)
        self.file_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_panel.setObjectName("file_panel")
        self.gridLayout = QtWidgets.QGridLayout(self.file_panel)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.file_panel)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.work_dir = QtWidgets.QLineEdit(self.file_panel)
        self.work_dir.setObjectName("work_dir")
        self.horizontalLayout_2.addWidget(self.work_dir)
        self.pushButton = QtWidgets.QPushButton(self.file_panel)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.file_panel)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setObjectName("groupBox")
        self.file_list = QtWidgets.QListWidget(self.groupBox)
        self.file_list.setGeometry(QtCore.QRect(0, 20, 491, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_list.sizePolicy().hasHeightForWidth())
        self.file_list.setSizePolicy(sizePolicy)
        self.file_list.setMinimumSize(QtCore.QSize(0, 120))
        self.file_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.file_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.file_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.file_list.setObjectName("file_list")
        self.verticalLayout.addWidget(self.groupBox)
        self.file_table = QtWidgets.QTableWidget(self.file_panel)
        self.file_table.setMaximumSize(QtCore.QSize(16777215, 125))
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(2)
        self.file_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.file_table)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.file_panel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.file_panel)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.file_panel)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.file_panel)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.file_panel)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.selected_list = QtWidgets.QListWidget(self.groupBox_2)
        self.selected_list.setGeometry(QtCore.QRect(5, 21, 481, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_list.sizePolicy().hasHeightForWidth())
        self.selected_list.setSizePolicy(sizePolicy)
        self.selected_list.setMinimumSize(QtCore.QSize(0, 80))
        self.selected_list.setObjectName("selected_list")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.file_panel)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphWidget = ImageView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(120)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout_3.addWidget(self.graphWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.file_panel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1553, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.add_target)
        self.pushButton_3.clicked.connect(MainWindow.remove_target)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Path:"))
        self.pushButton.setText(_translate("MainWindow", "browse"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        item = self.file_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "filename"))
        item = self.file_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "num"))
        self.label.setText(_translate("MainWindow", "Target:"))
        self.pushButton_2.setText(_translate("MainWindow", "add"))
        self.pushButton_3.setText(_translate("MainWindow", "remove"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SAXS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

from pyqtgraph import ImageView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

