# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xpcs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from .plothandler import MplCanvas, MplCanvasBarH, MplCanvasBarV, ImageViewDev

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1680, 949)
        mainwindow.setMinimumSize(QtCore.QSize(1024, 800))
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.file_panel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_panel.sizePolicy().hasHeightForWidth())
        self.file_panel.setSizePolicy(sizePolicy)
        self.file_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_panel.setObjectName("file_panel")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.file_panel)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.splitter_4 = QtWidgets.QSplitter(self.file_panel)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.work_dir = QtWidgets.QLineEdit(self.layoutWidget)
        self.work_dir.setMinimumSize(QtCore.QSize(200, 0))
        self.work_dir.setMaximumSize(QtCore.QSize(480, 16777215))
        self.work_dir.setClearButtonEnabled(True)
        self.work_dir.setObjectName("work_dir")
        self.horizontalLayout_6.addWidget(self.work_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.box_source = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_source.sizePolicy().hasHeightForWidth())
        self.box_source.setSizePolicy(sizePolicy)
        self.box_source.setMinimumSize(QtCore.QSize(0, 80))
        self.box_source.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.box_source.setObjectName("box_source")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.box_source)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.list_view_source = QtWidgets.QListWidget(self.box_source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.list_view_source.sizePolicy().hasHeightForWidth())
        self.list_view_source.setSizePolicy(sizePolicy)
        self.list_view_source.setMinimumSize(QtCore.QSize(0, 120))
        self.list_view_source.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_view_source.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_view_source.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_view_source.setAlternatingRowColors(True)
        self.list_view_source.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.list_view_source.setObjectName("list_view_source")
        self.gridLayout_5.addWidget(self.list_view_source, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.box_source)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filter_str = QtWidgets.QLineEdit(self.layoutWidget1)
        self.filter_str.setMaximumSize(QtCore.QSize(480, 100))
        self.filter_str.setClearButtonEnabled(True)
        self.filter_str.setObjectName("filter_str")
        self.verticalLayout_2.addWidget(self.filter_str)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setMaximumSize(QtCore.QSize(160, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.box_target = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_target.sizePolicy().hasHeightForWidth())
        self.box_target.setSizePolicy(sizePolicy)
        self.box_target.setMinimumSize(QtCore.QSize(0, 120))
        self.box_target.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.box_target.setObjectName("box_target")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.box_target)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_view_target = QtWidgets.QListWidget(self.box_target)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.list_view_target.sizePolicy().hasHeightForWidth())
        self.list_view_target.setSizePolicy(sizePolicy)
        self.list_view_target.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.list_view_target.setDragEnabled(True)
        self.list_view_target.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.list_view_target.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_view_target.setAlternatingRowColors(True)
        self.list_view_target.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.list_view_target.setObjectName("list_view_target")
        self.gridLayout_4.addWidget(self.list_view_target, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.box_auto_update = QtWidgets.QCheckBox(self.box_target)
        self.box_auto_update.setChecked(True)
        self.box_auto_update.setObjectName("box_auto_update")
        self.horizontalLayout_7.addWidget(self.box_auto_update)
        self.btn_load_data = QtWidgets.QPushButton(self.box_target)
        self.btn_load_data.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load_data.sizePolicy().hasHeightForWidth())
        self.btn_load_data.setSizePolicy(sizePolicy)
        self.btn_load_data.setObjectName("btn_load_data")
        self.horizontalLayout_7.addWidget(self.btn_load_data)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_30 = QtWidgets.QLabel(self.box_target)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_9.addWidget(self.label_30)
        self.progress_bar = QtWidgets.QProgressBar(self.box_target)
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_9.addWidget(self.progress_bar)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.box_target)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1080, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1_1 = QtWidgets.QWidget()
        self.tab1_1.setObjectName("tab1_1")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.tab1_1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.pg_saxs = ImageViewDev(self.tab1_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(120)
        sizePolicy.setHeightForWidth(self.pg_saxs.sizePolicy().hasHeightForWidth())
        self.pg_saxs.setSizePolicy(sizePolicy)
        self.pg_saxs.setObjectName("pg_saxs")
        self.gridLayout_26.addWidget(self.pg_saxs, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab1_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.saxs2d_autorotate = QtWidgets.QCheckBox(self.groupBox_3)
        self.saxs2d_autorotate.setChecked(True)
        self.saxs2d_autorotate.setObjectName("saxs2d_autorotate")
        self.gridLayout_3.addWidget(self.saxs2d_autorotate, 0, 4, 1, 1)
        self.cb_saxs2D_type = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_saxs2D_type.setObjectName("cb_saxs2D_type")
        self.cb_saxs2D_type.addItem("")
        self.cb_saxs2D_type.addItem("")
        self.gridLayout_3.addWidget(self.cb_saxs2D_type, 0, 1, 1, 1)
        self.cb_saxs2D_cmap = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_saxs2D_cmap.setObjectName("cb_saxs2D_cmap")
        self.cb_saxs2D_cmap.addItem("")
        self.cb_saxs2D_cmap.addItem("")
        self.cb_saxs2D_cmap.addItem("")
        self.cb_saxs2D_cmap.addItem("")
        self.cb_saxs2D_cmap.addItem("")
        self.cb_saxs2D_cmap.addItem("")
        self.gridLayout_3.addWidget(self.cb_saxs2D_cmap, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 0, 1, 6)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.saxs2d_flag = QtWidgets.QLabel(self.groupBox_3)
        self.saxs2d_flag.setObjectName("saxs2d_flag")
        self.gridLayout_3.addWidget(self.saxs2d_flag, 0, 5, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab1_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_24.addWidget(self.label_21, 0, 0, 1, 1)
        self.cb_saxs_type = QtWidgets.QComboBox(self.groupBox_6)
        self.cb_saxs_type.setObjectName("cb_saxs_type")
        self.cb_saxs_type.addItem("")
        self.cb_saxs_type.addItem("")
        self.cb_saxs_type.addItem("")
        self.cb_saxs_type.addItem("")
        self.gridLayout_24.addWidget(self.cb_saxs_type, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_24.addWidget(self.label_22, 0, 2, 1, 1)
        self.sb_saxs_offset = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.sb_saxs_offset.setDecimals(4)
        self.sb_saxs_offset.setSingleStep(0.05)
        self.sb_saxs_offset.setProperty("value", 0.0)
        self.sb_saxs_offset.setObjectName("sb_saxs_offset")
        self.gridLayout_24.addWidget(self.sb_saxs_offset, 0, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setObjectName("label_23")
        self.gridLayout_24.addWidget(self.label_23, 0, 4, 1, 1)
        self.cb_saxs_norm = QtWidgets.QComboBox(self.groupBox_6)
        self.cb_saxs_norm.setObjectName("cb_saxs_norm")
        self.cb_saxs_norm.addItem("")
        self.cb_saxs_norm.addItem("")
        self.cb_saxs_norm.addItem("")
        self.cb_saxs_norm.addItem("")
        self.gridLayout_24.addWidget(self.cb_saxs_norm, 0, 5, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_24.addWidget(self.pushButton_10, 1, 0, 1, 6)
        self.gridLayout_16.addLayout(self.gridLayout_24, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.mp_saxs = MplCanvasBarV(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mp_saxs.sizePolicy().hasHeightForWidth())
        self.mp_saxs.setSizePolicy(sizePolicy)
        self.mp_saxs.setMinimumSize(QtCore.QSize(600, 0))
        self.mp_saxs.setObjectName("mp_saxs")
        self.gridLayout_25.addWidget(self.mp_saxs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mp_stab = MplCanvas(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mp_stab.sizePolicy().hasHeightForWidth())
        self.mp_stab.setSizePolicy(sizePolicy)
        self.mp_stab.setObjectName("mp_stab")
        self.gridLayout_6.addWidget(self.mp_stab, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_stab = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_stab.setObjectName("cb_stab")
        self.verticalLayout_3.addWidget(self.cb_stab)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_20.addWidget(self.label_16, 1, 4, 1, 1)
        self.cb_stab_norm = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_stab_norm.setObjectName("cb_stab_norm")
        self.cb_stab_norm.addItem("")
        self.cb_stab_norm.addItem("")
        self.cb_stab_norm.addItem("")
        self.cb_stab_norm.addItem("")
        self.gridLayout_20.addWidget(self.cb_stab_norm, 1, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_20.addWidget(self.label_14, 1, 0, 1, 1)
        self.cb_stab_type = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_stab_type.setObjectName("cb_stab_type")
        self.cb_stab_type.addItem("")
        self.cb_stab_type.addItem("")
        self.cb_stab_type.addItem("")
        self.cb_stab_type.addItem("")
        self.gridLayout_20.addWidget(self.cb_stab_type, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_20.addWidget(self.label_24, 1, 2, 1, 1)
        self.sb_stab_offset = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_stab_offset.setDecimals(4)
        self.sb_stab_offset.setSingleStep(0.05)
        self.sb_stab_offset.setProperty("value", 0.0)
        self.sb_stab_offset.setObjectName("sb_stab_offset")
        self.gridLayout_20.addWidget(self.sb_stab_offset, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_20)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.gridLayout_17.addLayout(self.verticalLayout_3, 0, 1, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(357, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.pg_intt = MplCanvas(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pg_intt.sizePolicy().hasHeightForWidth())
        self.pg_intt.setSizePolicy(sizePolicy)
        self.pg_intt.setObjectName("pg_intt")
        self.gridLayout_27.addWidget(self.pg_intt, 0, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(581, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem6, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.sb_intt_sampling = QtWidgets.QSpinBox(self.groupBox_7)
        self.sb_intt_sampling.setProperty("value", 20)
        self.sb_intt_sampling.setObjectName("sb_intt_sampling")
        self.gridLayout_23.addWidget(self.sb_intt_sampling, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_23.addWidget(self.label_11, 0, 4, 1, 1)
        self.btn_intt = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_intt.setObjectName("btn_intt")
        self.gridLayout_23.addWidget(self.btn_intt, 1, 0, 1, 6)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_23.addWidget(self.label_9, 0, 0, 1, 1)
        self.sb_intt_max = QtWidgets.QSpinBox(self.groupBox_7)
        self.sb_intt_max.setProperty("value", 10)
        self.sb_intt_max.setObjectName("sb_intt_max")
        self.gridLayout_23.addWidget(self.sb_intt_max, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_23.addWidget(self.label_31, 0, 2, 1, 1)
        self.sb_window = QtWidgets.QSpinBox(self.groupBox_7)
        self.sb_window.setMaximum(999)
        self.sb_window.setProperty("value", 10)
        self.sb_window.setObjectName("sb_window")
        self.gridLayout_23.addWidget(self.sb_window, 0, 3, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_7, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(580, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem7, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.avg_intt_num_clusters = QtWidgets.QSpinBox(self.groupBox_9)
        self.avg_intt_num_clusters.setMinimum(1)
        self.avg_intt_num_clusters.setMaximum(20)
        self.avg_intt_num_clusters.setProperty("value", 2)
        self.avg_intt_num_clusters.setObjectName("avg_intt_num_clusters")
        self.horizontalLayout_3.addWidget(self.avg_intt_num_clusters)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.gridLayout_30.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.mp_avg_intt = MplCanvas(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.mp_avg_intt.sizePolicy().hasHeightForWidth())
        self.mp_avg_intt.setSizePolicy(sizePolicy)
        self.mp_avg_intt.setMinimumSize(QtCore.QSize(0, 500))
        self.mp_avg_intt.setObjectName("mp_avg_intt")
        self.gridLayout_30.addWidget(self.mp_avg_intt, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.mp_avg_g2 = MplCanvas(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.mp_avg_g2.sizePolicy().hasHeightForWidth())
        self.mp_avg_g2.setSizePolicy(sizePolicy)
        self.mp_avg_g2.setMinimumSize(QtCore.QSize(0, 500))
        self.mp_avg_g2.setObjectName("mp_avg_g2")
        self.gridLayout_36.addWidget(self.mp_avg_g2, 0, 0, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_10)
        self.label_32.setObjectName("label_32")
        self.gridLayout_31.addWidget(self.label_32, 0, 0, 1, 1)
        self.avg_qindex = QtWidgets.QSpinBox(self.groupBox_10)
        self.avg_qindex.setMaximum(999)
        self.avg_qindex.setProperty("value", 5)
        self.avg_qindex.setObjectName("avg_qindex")
        self.gridLayout_31.addWidget(self.avg_qindex, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setObjectName("label_33")
        self.gridLayout_31.addWidget(self.label_33, 0, 2, 1, 1)
        self.avg_window = QtWidgets.QSpinBox(self.groupBox_10)
        self.avg_window.setMinimum(1)
        self.avg_window.setProperty("value", 10)
        self.avg_window.setObjectName("avg_window")
        self.gridLayout_31.addWidget(self.avg_window, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_10)
        self.label_26.setObjectName("label_26")
        self.gridLayout_31.addWidget(self.label_26, 1, 0, 1, 2)
        self.avg_blmin = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.avg_blmin.setSpecialValueText("")
        self.avg_blmin.setDecimals(3)
        self.avg_blmin.setMaximum(10.0)
        self.avg_blmin.setSingleStep(0.01)
        self.avg_blmin.setProperty("value", 0.95)
        self.avg_blmin.setObjectName("avg_blmin")
        self.gridLayout_31.addWidget(self.avg_blmin, 1, 2, 1, 1)
        self.avg_blmax = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.avg_blmax.setDecimals(3)
        self.avg_blmax.setMinimum(0.9)
        self.avg_blmax.setMaximum(10.0)
        self.avg_blmax.setSingleStep(0.01)
        self.avg_blmax.setProperty("value", 1.05)
        self.avg_blmax.setObjectName("avg_blmax")
        self.gridLayout_31.addWidget(self.avg_blmax, 1, 3, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_31, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_35.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_35, 1, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_28.addWidget(self.label_17, 0, 0, 1, 1)
        self.cb_avg_chunk_size = QtWidgets.QComboBox(self.groupBox_8)
        self.cb_avg_chunk_size.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cb_avg_chunk_size.setObjectName("cb_avg_chunk_size")
        self.cb_avg_chunk_size.addItem("")
        self.cb_avg_chunk_size.addItem("")
        self.cb_avg_chunk_size.addItem("")
        self.cb_avg_chunk_size.addItem("")
        self.cb_avg_chunk_size.addItem("")
        self.gridLayout_28.addWidget(self.cb_avg_chunk_size, 0, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_28.addWidget(self.label_20, 1, 0, 1, 1)
        self.avg_save_path = QtWidgets.QLineEdit(self.groupBox_8)
        self.avg_save_path.setClearButtonEnabled(True)
        self.avg_save_path.setObjectName("avg_save_path")
        self.gridLayout_28.addWidget(self.avg_save_path, 1, 1, 1, 2)
        self.avg_use_source_path = QtWidgets.QCheckBox(self.groupBox_8)
        self.avg_use_source_path.setChecked(True)
        self.avg_use_source_path.setObjectName("avg_use_source_path")
        self.gridLayout_28.addWidget(self.avg_use_source_path, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_28.addWidget(self.label_19, 2, 0, 1, 1)
        self.avg_save_name = QtWidgets.QLineEdit(self.groupBox_8)
        self.avg_save_name.setClearButtonEnabled(True)
        self.avg_save_name.setObjectName("avg_save_name")
        self.gridLayout_28.addWidget(self.avg_save_name, 2, 1, 1, 2)
        self.avg_no_overwrite = QtWidgets.QCheckBox(self.groupBox_8)
        self.avg_no_overwrite.setObjectName("avg_no_overwrite")
        self.gridLayout_28.addWidget(self.avg_no_overwrite, 2, 3, 1, 1)
        self.btn_start_avg = QtWidgets.QPushButton(self.groupBox_8)
        self.btn_start_avg.setObjectName("btn_start_avg")
        self.gridLayout_28.addWidget(self.btn_start_avg, 3, 0, 1, 2)
        self.avg_progressbar = QtWidgets.QProgressBar(self.groupBox_8)
        self.avg_progressbar.setProperty("value", 0)
        self.avg_progressbar.setObjectName("avg_progressbar")
        self.gridLayout_28.addWidget(self.avg_progressbar, 3, 2, 1, 2)
        self.gridLayout_29.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.g2_scroll_area = QtWidgets.QWidget()
        self.g2_scroll_area.setGeometry(QtCore.QRect(0, 0, 98, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_scroll_area.sizePolicy().hasHeightForWidth())
        self.g2_scroll_area.setSizePolicy(sizePolicy)
        self.g2_scroll_area.setObjectName("g2_scroll_area")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.g2_scroll_area)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.mp_g2 = MplCanvasBarV(self.g2_scroll_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.mp_g2.sizePolicy().hasHeightForWidth())
        self.mp_g2.setSizePolicy(sizePolicy)
        self.mp_g2.setMinimumSize(QtCore.QSize(0, 0))
        self.mp_g2.setObjectName("mp_g2")
        self.gridLayout_10.addWidget(self.mp_g2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.g2_scroll_area)
        self.gridLayout_9.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 125))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.g2_ymin = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_ymin.sizePolicy().hasHeightForWidth())
        self.g2_ymin.setSizePolicy(sizePolicy)
        self.g2_ymin.setObjectName("g2_ymin")
        self.gridLayout_11.addWidget(self.g2_ymin, 2, 1, 1, 1)
        self.g2_qmin = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_qmin.sizePolicy().hasHeightForWidth())
        self.g2_qmin.setSizePolicy(sizePolicy)
        self.g2_qmin.setObjectName("g2_qmin")
        self.gridLayout_11.addWidget(self.g2_qmin, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 2, 0, 1, 1)
        self.g2_tmin = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_tmin.sizePolicy().hasHeightForWidth())
        self.g2_tmin.setSizePolicy(sizePolicy)
        self.g2_tmin.setObjectName("g2_tmin")
        self.gridLayout_11.addWidget(self.g2_tmin, 1, 1, 1, 1)
        self.g2_qmax = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_qmax.sizePolicy().hasHeightForWidth())
        self.g2_qmax.setSizePolicy(sizePolicy)
        self.g2_qmax.setObjectName("g2_qmax")
        self.gridLayout_11.addWidget(self.g2_qmax, 0, 2, 1, 1)
        self.g2_tmax = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_tmax.sizePolicy().hasHeightForWidth())
        self.g2_tmax.setSizePolicy(sizePolicy)
        self.g2_tmax.setObjectName("g2_tmax")
        self.gridLayout_11.addWidget(self.g2_tmax, 1, 2, 1, 1)
        self.g2_ymax = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_ymax.sizePolicy().hasHeightForWidth())
        self.g2_ymax.setSizePolicy(sizePolicy)
        self.g2_ymax.setObjectName("g2_ymax")
        self.gridLayout_11.addWidget(self.g2_ymax, 2, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_19.addWidget(self.pushButton_4, 0, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_19.addWidget(self.label_8, 1, 0, 1, 1)
        self.sb_g2_column = QtWidgets.QSpinBox(self.groupBox)
        self.sb_g2_column.setMinimum(1)
        self.sb_g2_column.setMaximum(8)
        self.sb_g2_column.setSingleStep(1)
        self.sb_g2_column.setProperty("value", 4)
        self.sb_g2_column.setObjectName("sb_g2_column")
        self.gridLayout_19.addWidget(self.sb_g2_column, 1, 1, 1, 1)
        self.g2_show_label = QtWidgets.QCheckBox(self.groupBox)
        self.g2_show_label.setObjectName("g2_show_label")
        self.gridLayout_19.addWidget(self.g2_show_label, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_19.addWidget(self.label, 2, 0, 1, 1)
        self.sb_g2_offset = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_g2_offset.setDecimals(3)
        self.sb_g2_offset.setSingleStep(0.005)
        self.sb_g2_offset.setObjectName("sb_g2_offset")
        self.gridLayout_19.addWidget(self.sb_g2_offset, 2, 1, 1, 1)
        self.g2_show_fit = QtWidgets.QCheckBox(self.groupBox)
        self.g2_show_fit.setObjectName("g2_show_fit")
        self.gridLayout_19.addWidget(self.g2_show_fit, 2, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 125))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.g2_err_msg = QtWidgets.QPlainTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g2_err_msg.sizePolicy().hasHeightForWidth())
        self.g2_err_msg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.g2_err_msg.setFont(font)
        self.g2_err_msg.setObjectName("g2_err_msg")
        self.gridLayout_14.addWidget(self.g2_err_msg, 0, 1, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tau_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.tau_max.setObjectName("tau_max")
        self.gridLayout_15.addWidget(self.tau_max, 0, 2, 1, 1)
        self.cts_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.cts_max.setObjectName("cts_max")
        self.gridLayout_15.addWidget(self.cts_max, 1, 2, 1, 1)
        self.tau_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.tau_min.setObjectName("tau_min")
        self.gridLayout_15.addWidget(self.tau_min, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 1, 0, 1, 1)
        self.bkg_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.bkg_max.setObjectName("bkg_max")
        self.gridLayout_15.addWidget(self.bkg_max, 2, 2, 1, 1)
        self.cts_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.cts_min.setObjectName("cts_min")
        self.gridLayout_15.addWidget(self.cts_min, 1, 1, 1, 1)
        self.bkg_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.bkg_min.setObjectName("bkg_min")
        self.gridLayout_15.addWidget(self.bkg_min, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 120))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setMinimumSize(QtCore.QSize(120, 80))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_21.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 1, 0, 1, 1)
        self.sb_tauq_qmax = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.sb_tauq_qmax.setDecimals(4)
        self.sb_tauq_qmax.setMinimum(0.0)
        self.sb_tauq_qmax.setMaximum(2.0)
        self.sb_tauq_qmax.setSingleStep(0.001)
        self.sb_tauq_qmax.setProperty("value", 0.0092)
        self.sb_tauq_qmax.setObjectName("sb_tauq_qmax")
        self.gridLayout_12.addWidget(self.sb_tauq_qmax, 0, 1, 1, 1)
        self.sb_tauq_offset = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.sb_tauq_offset.setMinimum(-2.0)
        self.sb_tauq_offset.setMaximum(2.0)
        self.sb_tauq_offset.setSingleStep(0.2)
        self.sb_tauq_offset.setProperty("value", 0.25)
        self.sb_tauq_offset.setObjectName("sb_tauq_offset")
        self.gridLayout_12.addWidget(self.sb_tauq_offset, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.tauq_msg = QtWidgets.QTextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tauq_msg.sizePolicy().hasHeightForWidth())
        self.tauq_msg.setSizePolicy(sizePolicy)
        self.tauq_msg.setMinimumSize(QtCore.QSize(100, 0))
        self.tauq_msg.setObjectName("tauq_msg")
        self.gridLayout_21.addWidget(self.tauq_msg, 0, 2, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.mp_tauq = MplCanvas(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mp_tauq.sizePolicy().hasHeightForWidth())
        self.mp_tauq.setSizePolicy(sizePolicy)
        self.mp_tauq.setObjectName("mp_tauq")
        self.gridLayout_22.addWidget(self.mp_tauq, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.splitter_5 = QtWidgets.QSplitter(self.tab_8)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.mp_2t_map = MplCanvasBarH(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.mp_2t_map.sizePolicy().hasHeightForWidth())
        self.mp_2t_map.setSizePolicy(sizePolicy)
        self.mp_2t_map.setMinimumSize(QtCore.QSize(300, 200))
        self.mp_2t_map.setObjectName("mp_2t_map")
        self.mp_2t = MplCanvasBarH(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.mp_2t.sizePolicy().hasHeightForWidth())
        self.mp_2t.setSizePolicy(sizePolicy)
        self.mp_2t.setMinimumSize(QtCore.QSize(300, 200))
        self.mp_2t.setObjectName("mp_2t")
        self.gridLayout_33.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.label_29 = QtWidgets.QLabel(self.groupBox_11)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_8.addWidget(self.label_29)
        self.cb_twotime_group = QtWidgets.QComboBox(self.groupBox_11)
        self.cb_twotime_group.setObjectName("cb_twotime_group")
        self.horizontalLayout_8.addWidget(self.cb_twotime_group)
        self.label_27 = QtWidgets.QLabel(self.groupBox_11)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.twotime_q_index = QtWidgets.QSpinBox(self.groupBox_11)
        self.twotime_q_index.setMinimum(0)
        self.twotime_q_index.setMaximum(9999)
        self.twotime_q_index.setProperty("value", 3)
        self.twotime_q_index.setObjectName("twotime_q_index")
        self.horizontalLayout_8.addWidget(self.twotime_q_index)
        self.label_28 = QtWidgets.QLabel(self.groupBox_11)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_8.addWidget(self.label_28)
        self.cb_twotime_cmap = QtWidgets.QComboBox(self.groupBox_11)
        self.cb_twotime_cmap.setObjectName("cb_twotime_cmap")
        self.cb_twotime_cmap.addItem("")
        self.cb_twotime_cmap.addItem("")
        self.cb_twotime_cmap.addItem("")
        self.cb_twotime_cmap.addItem("")
        self.cb_twotime_cmap.addItem("")
        self.cb_twotime_cmap.addItem("")
        self.horizontalLayout_8.addWidget(self.cb_twotime_cmap)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_8.addWidget(self.pushButton_12)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_33.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.hdf_info = QtWidgets.QTextBrowser(self.tab_9)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.hdf_info.setFont(font)
        self.hdf_info.setObjectName("hdf_info")
        self.gridLayout_7.addWidget(self.hdf_info, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.hdf_list = QtWidgets.QComboBox(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hdf_list.sizePolicy().hasHeightForWidth())
        self.hdf_list.setSizePolicy(sizePolicy)
        self.hdf_list.setMinimumSize(QtCore.QSize(450, 0))
        self.hdf_list.setObjectName("hdf_list")
        self.horizontalLayout_5.addWidget(self.hdf_list)
        self.hdf_key_filter = QtWidgets.QLineEdit(self.tab_9)
        self.hdf_key_filter.setMinimumSize(QtCore.QSize(360, 0))
        self.hdf_key_filter.setClearButtonEnabled(True)
        self.hdf_key_filter.setObjectName("hdf_key_filter")
        self.horizontalLayout_5.addWidget(self.hdf_key_filter)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.console_panel = QtWidgets.QWidget(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.console_panel.sizePolicy().hasHeightForWidth())
        self.console_panel.setSizePolicy(sizePolicy)
        self.console_panel.setObjectName("console_panel")
        self.gridLayout_34.addWidget(self.console_panel, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, "")
        self.gridLayout_32.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.file_panel, 0, 0, 1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 22))
        self.menubar.setObjectName("menubar")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainwindow)
        self.tabWidget.setCurrentIndex(4)
        self.cb_saxs_type.setCurrentIndex(3)
        self.cb_stab_norm.setCurrentIndex(0)
        self.cb_stab_type.setCurrentIndex(3)
        self.cb_avg_chunk_size.setCurrentIndex(2)
        self.pushButton_2.clicked.connect(mainwindow.add_target)
        self.pushButton_3.clicked.connect(mainwindow.remove_target)
        self.pushButton.clicked.connect(mainwindow.load_path)
        self.filter_str.textChanged['QString'].connect(mainwindow.trie_search)
        self.filter_str.returnPressed.connect(self.pushButton_2.click)
        self.btn_load_data.clicked.connect(mainwindow.load_data)
        self.cts_max.editingFinished.connect(mainwindow.check_number)
        self.pushButton_4.clicked.connect(mainwindow.plot_g2)
        self.tau_max.editingFinished.connect(mainwindow.check_number)
        self.bkg_max.editingFinished.connect(mainwindow.check_number)
        self.tau_min.editingFinished.connect(mainwindow.check_number)
        self.bkg_min.editingFinished.connect(mainwindow.check_number)
        self.cts_min.editingFinished.connect(mainwindow.check_number)
        self.hdf_list.currentIndexChanged['int'].connect(mainwindow.show_hdf_info)
        self.hdf_key_filter.returnPressed.connect(mainwindow.show_hdf_info)
        self.pushButton_7.clicked.connect(mainwindow.plot_stability_iq)
        self.pushButton_8.clicked.connect(mainwindow.plot_tauq)
        self.pushButton_5.clicked.connect(mainwindow.plot_saxs_2D)
        self.pushButton_10.clicked.connect(mainwindow.plot_saxs_1D)
        self.g2_qmin.editingFinished.connect(mainwindow.check_g2_number)
        self.g2_qmax.editingFinished.connect(mainwindow.check_g2_number)
        self.g2_tmin.editingFinished.connect(mainwindow.check_g2_number)
        self.g2_tmax.editingFinished.connect(mainwindow.check_g2_number)
        self.g2_ymin.editingFinished.connect(mainwindow.check_g2_number)
        self.g2_ymax.editingFinished.connect(mainwindow.check_g2_number)
        self.btn_intt.clicked.connect(mainwindow.plot_intt)
        self.btn_start_avg.clicked.connect(mainwindow.do_average)
        self.pushButton_9.clicked.connect(mainwindow.plot_outlier_g2)
        self.pushButton_6.clicked.connect(mainwindow.plot_outlier_intt)
        self.pushButton_11.clicked.connect(mainwindow.reload_source)
        self.pushButton_12.clicked['bool'].connect(mainwindow.plot_twotime)
        self.twotime_q_index.valueChanged['int'].connect(mainwindow.plot_twotime)
        self.cb_twotime_cmap.currentIndexChanged['int'].connect(mainwindow.plot_twotime)
        self.box_auto_update.stateChanged['int'].connect(mainwindow.load_data)
        self.cb_saxs_type.currentIndexChanged['int'].connect(self.pushButton_10.click)
        self.sb_saxs_offset.valueChanged['double'].connect(self.pushButton_10.click)
        self.cb_saxs_norm.currentIndexChanged['int'].connect(self.pushButton_10.click)
        self.cb_stab_type.currentIndexChanged['int'].connect(self.pushButton_7.click)
        self.sb_stab_offset.valueChanged['double'].connect(self.pushButton_7.click)
        self.cb_stab_norm.currentIndexChanged['int'].connect(self.pushButton_7.click)
        self.cb_stab.currentIndexChanged['int'].connect(self.pushButton_7.click)
        self.sb_intt_max.valueChanged['int'].connect(self.btn_intt.click)
        self.sb_intt_sampling.valueChanged['int'].connect(self.btn_intt.click)
        self.avg_intt_num_clusters.valueChanged['int'].connect(self.pushButton_6.click)
        self.avg_blmax.valueChanged['double'].connect(self.pushButton_9.click)
        self.cb_saxs2D_type.currentIndexChanged['int'].connect(self.pushButton_5.click)
        self.cb_saxs2D_cmap.currentIndexChanged['int'].connect(self.pushButton_5.click)
        self.saxs2d_autorotate.stateChanged['int'].connect(self.pushButton_5.click)
        self.sb_window.valueChanged['int'].connect(self.btn_intt.click)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "XPCS_Viewer"))
        self.label_2.setText(_translate("mainwindow", "Path:"))
        self.pushButton.setText(_translate("mainwindow", "browse"))
        self.pushButton_11.setText(_translate("mainwindow", "reload"))
        self.box_source.setTitle(_translate("mainwindow", "Source:"))
        self.filter_str.setPlaceholderText(_translate("mainwindow", "prefix filter, press enter to add files"))
        self.pushButton_2.setText(_translate("mainwindow", "add"))
        self.pushButton_3.setText(_translate("mainwindow", "remove"))
        self.box_target.setTitle(_translate("mainwindow", "Target:"))
        self.box_auto_update.setText(_translate("mainwindow", "auto"))
        self.btn_load_data.setText(_translate("mainwindow", "update"))
        self.label_30.setText(_translate("mainwindow", "progress:"))
        self.groupBox_3.setTitle(_translate("mainwindow", "SAXS 2D Plot Setting"))
        self.saxs2d_autorotate.setText(_translate("mainwindow", "auto-rotate?"))
        self.cb_saxs2D_type.setItemText(0, _translate("mainwindow", "log"))
        self.cb_saxs2D_type.setItemText(1, _translate("mainwindow", "linear"))
        self.cb_saxs2D_cmap.setItemText(0, _translate("mainwindow", "jet"))
        self.cb_saxs2D_cmap.setItemText(1, _translate("mainwindow", "hot"))
        self.cb_saxs2D_cmap.setItemText(2, _translate("mainwindow", "plasma"))
        self.cb_saxs2D_cmap.setItemText(3, _translate("mainwindow", "viridis"))
        self.cb_saxs2D_cmap.setItemText(4, _translate("mainwindow", "magma"))
        self.cb_saxs2D_cmap.setItemText(5, _translate("mainwindow", "gray"))
        self.label_13.setText(_translate("mainwindow", "colormap:"))
        self.pushButton_5.setText(_translate("mainwindow", "Plot 2D SAXS"))
        self.label_12.setText(_translate("mainwindow", "type:"))
        self.saxs2d_flag.setText(_translate("mainwindow", "None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1_1), _translate("mainwindow", "SAXS-2D"))
        self.groupBox_6.setTitle(_translate("mainwindow", "SAXS 1D Plot Setting"))
        self.label_21.setText(_translate("mainwindow", "type:"))
        self.cb_saxs_type.setItemText(0, _translate("mainwindow", "I - q"))
        self.cb_saxs_type.setItemText(1, _translate("mainwindow", "I - log(q)"))
        self.cb_saxs_type.setItemText(2, _translate("mainwindow", "log(I) - q"))
        self.cb_saxs_type.setItemText(3, _translate("mainwindow", "log(I) - log(q)"))
        self.label_22.setText(_translate("mainwindow", "offset:"))
        self.label_23.setText(_translate("mainwindow", "normalization:"))
        self.cb_saxs_norm.setItemText(0, _translate("mainwindow", "none"))
        self.cb_saxs_norm.setItemText(1, _translate("mainwindow", "I\' = Iq2"))
        self.cb_saxs_norm.setItemText(2, _translate("mainwindow", "I\' = Iq4"))
        self.cb_saxs_norm.setItemText(3, _translate("mainwindow", "I\' = I/Io"))
        self.pushButton_10.setText(_translate("mainwindow", "Plot 1D SAXS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainwindow", "SAXS-1D"))
        self.groupBox_4.setTitle(_translate("mainwindow", "Stability Plot Setting"))
        self.label_16.setText(_translate("mainwindow", "normalization:"))
        self.cb_stab_norm.setItemText(0, _translate("mainwindow", "none"))
        self.cb_stab_norm.setItemText(1, _translate("mainwindow", "I\' = Iq2"))
        self.cb_stab_norm.setItemText(2, _translate("mainwindow", "I\' = Iq4"))
        self.cb_stab_norm.setItemText(3, _translate("mainwindow", "I\' = I/Io"))
        self.label_14.setText(_translate("mainwindow", "type:"))
        self.cb_stab_type.setItemText(0, _translate("mainwindow", "I - q"))
        self.cb_stab_type.setItemText(1, _translate("mainwindow", "I - log(q)"))
        self.cb_stab_type.setItemText(2, _translate("mainwindow", "log(I) - q"))
        self.cb_stab_type.setItemText(3, _translate("mainwindow", "log(I) - log(q)"))
        self.label_24.setText(_translate("mainwindow", "offset:"))
        self.pushButton_7.setText(_translate("mainwindow", "Plot Iq Stability Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainwindow", "Stability"))
        self.groupBox_7.setTitle(_translate("mainwindow", "Setting"))
        self.label_11.setText(_translate("mainwindow", "sampling:"))
        self.btn_intt.setText(_translate("mainwindow", "plot Intensity-T"))
        self.label_9.setText(_translate("mainwindow", "max points:"))
        self.label_31.setText(_translate("mainwindow", "avg window:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainwindow", "Intensity-T"))
        self.groupBox_9.setTitle(_translate("mainwindow", "Intensity-T outliner"))
        self.label_25.setText(_translate("mainwindow", "num_clusters:"))
        self.pushButton_6.setText(_translate("mainwindow", "replot"))
        self.groupBox_10.setTitle(_translate("mainwindow", "g2 outlier"))
        self.label_32.setText(_translate("mainwindow", "q_index:"))
        self.label_33.setText(_translate("mainwindow", "avg_window:"))
        self.label_26.setText(_translate("mainwindow", "baseline cutoff: [min - max]"))
        self.pushButton_9.setText(_translate("mainwindow", "replot"))
        self.groupBox_8.setTitle(_translate("mainwindow", "Averaging setting:"))
        self.label_17.setText(_translate("mainwindow", "batch size:"))
        self.cb_avg_chunk_size.setItemText(0, _translate("mainwindow", "32"))
        self.cb_avg_chunk_size.setItemText(1, _translate("mainwindow", "64"))
        self.cb_avg_chunk_size.setItemText(2, _translate("mainwindow", "128"))
        self.cb_avg_chunk_size.setItemText(3, _translate("mainwindow", "256"))
        self.cb_avg_chunk_size.setItemText(4, _translate("mainwindow", "512"))
        self.label_20.setText(_translate("mainwindow", "save path:"))
        self.avg_use_source_path.setText(_translate("mainwindow", "using source path"))
        self.label_19.setText(_translate("mainwindow", "save name:"))
        self.avg_no_overwrite.setText(_translate("mainwindow", "no overwrite"))
        self.btn_start_avg.setText(_translate("mainwindow", "start average"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("mainwindow", "Average"))
        self.groupBox.setTitle(_translate("mainwindow", "Data Selection:"))
        self.g2_ymin.setText(_translate("mainwindow", "0.98"))
        self.g2_ymin.setPlaceholderText(_translate("mainwindow", "min"))
        self.g2_qmin.setText(_translate("mainwindow", "0"))
        self.g2_qmin.setPlaceholderText(_translate("mainwindow", "min"))
        self.label_3.setText(_translate("mainwindow", "q (1/Å):"))
        self.label_4.setText(_translate("mainwindow", "t range:"))
        self.label_7.setText(_translate("mainwindow", "y range"))
        self.g2_tmin.setText(_translate("mainwindow", "2E-6"))
        self.g2_tmin.setPlaceholderText(_translate("mainwindow", "min"))
        self.g2_qmax.setText(_translate("mainwindow", "0.0092"))
        self.g2_qmax.setPlaceholderText(_translate("mainwindow", "max"))
        self.g2_tmax.setText(_translate("mainwindow", "0.5"))
        self.g2_tmax.setPlaceholderText(_translate("mainwindow", "max"))
        self.g2_ymax.setText(_translate("mainwindow", "1.20"))
        self.g2_ymax.setPlaceholderText(_translate("mainwindow", "max"))
        self.pushButton_4.setText(_translate("mainwindow", "plot"))
        self.label_8.setText(_translate("mainwindow", "column:"))
        self.g2_show_label.setText(_translate("mainwindow", "show label?"))
        self.label.setText(_translate("mainwindow", "offset:"))
        self.g2_show_fit.setText(_translate("mainwindow", "show fit?"))
        self.groupBox_2.setTitle(_translate("mainwindow", "Single Exp Fitting Bounds:"))
        self.g2_err_msg.setPlaceholderText(_translate("mainwindow", "Fit error message"))
        self.tau_max.setText(_translate("mainwindow", "1.00e-2"))
        self.tau_max.setPlaceholderText(_translate("mainwindow", "max"))
        self.cts_max.setText(_translate("mainwindow", "0.20"))
        self.cts_max.setPlaceholderText(_translate("mainwindow", "max"))
        self.tau_min.setText(_translate("mainwindow", "1.00e-6"))
        self.tau_min.setPlaceholderText(_translate("mainwindow", "min"))
        self.label_6.setText(_translate("mainwindow", "contrast: "))
        self.bkg_max.setText(_translate("mainwindow", "1.05"))
        self.bkg_max.setPlaceholderText(_translate("mainwindow", "max"))
        self.cts_min.setText(_translate("mainwindow", "0.01"))
        self.cts_min.setPlaceholderText(_translate("mainwindow", "min"))
        self.bkg_min.setText(_translate("mainwindow", "0.95"))
        self.bkg_min.setPlaceholderText(_translate("mainwindow", "min"))
        self.label_10.setText(_translate("mainwindow", "bkg:"))
        self.label_5.setText(_translate("mainwindow", "tau:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("mainwindow", "g2"))
        self.groupBox_5.setTitle(_translate("mainwindow", "Data Selection:"))
        self.pushButton_8.setText(_translate("mainwindow", "fit plot"))
        self.label_18.setText(_translate("mainwindow", "Offset:"))
        self.label_15.setText(_translate("mainwindow", "Max q (1/Å):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("mainwindow", "Diffusion"))
        self.groupBox_11.setTitle(_translate("mainwindow", "Twotime Setting"))
        self.label_29.setText(_translate("mainwindow", "Group:"))
        self.label_27.setText(_translate("mainwindow", "q_index:"))
        self.label_28.setText(_translate("mainwindow", "colormap:"))
        self.cb_twotime_cmap.setItemText(0, _translate("mainwindow", "jet"))
        self.cb_twotime_cmap.setItemText(1, _translate("mainwindow", "hot"))
        self.cb_twotime_cmap.setItemText(2, _translate("mainwindow", "plasma"))
        self.cb_twotime_cmap.setItemText(3, _translate("mainwindow", "viridis"))
        self.cb_twotime_cmap.setItemText(4, _translate("mainwindow", "magma"))
        self.cb_twotime_cmap.setItemText(5, _translate("mainwindow", "gray"))
        self.pushButton_12.setText(_translate("mainwindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("mainwindow", "Two Time"))
        self.hdf_key_filter.setPlaceholderText(_translate("mainwindow", "filter strings, seperate by space, press enter to apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("mainwindow", "Exp Setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("mainwindow", "Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())

