key = {
  "nexus": {
    "saxs_1d": "/xpcs/partition-mean-total",
    "Iqp": "/xpcs/partition-mean-partial",
    "ql_sta": "/xpcs/qmap/sqlist",
    "ql_dyn": "/xpcs/qmap/dqlist",
    "dqmap": "/xpcs/qmap/dqmap",
    "sqmap": "/xpcs/qmap/sqmap",
    "mask": "/xpcs/qmap/mask",
    "type": "/xpcs/qmap/analysis_type",
    "avg_frames": "/xpcs/qmap/avg_frames",
    "stride_frames": "/xpcs/qmap/stride_frames",
    "tau": "/xpcs/tau",
    "g2": "/xpcs/norm-0-g2",
    "g2_err": "/xpcs/norm-0-stderr",
    "saxs_2d": "/xpcs/pixelSum",
    "Int_t": "/xpcs/frameSum",
    "c2_half": "/xpcs/C2T_all",
    "g2_full": "/xpcs/g2full",
    "g2_partials": "/xpcs/g2partials",
    "G2": "/xpcs/G2",
    "IP": "/xpcs/IP",
    "IF": "/xpcs/IF",
    "snophi": "/xpcs/qmap/snophi",
    "snoq": "/xpcs/qmap/snoq",
    "sphilist": "/xpcs/qmap/sphilist",
    "dnophi": "/xpcs/qmap/dnophi",
    "dnoq": "/xpcs/qmap/dnoq",
    "dphilist": "/xpcs/qmap/dphilist",
    "sphispan": "/xpcs/qmap/sphispan",
    "sqspan": "/xpcs/qmap/sqspan",
    # "abs_cross_section_scale": "/entry/instrument/bluesky/metadata/absolute_cross_section_scale",
    "t0": "/entry/instrument/detector_1/frame_time",
    "t1": "/entry/instrument/detector_1/count_time",
    # ---
    'X_energy': '/entry/instrument/incident_beam/incident_energy',
    'ccdx': '/entry/instrument/detector_1/position_x',
    'ccdy': '/entry/instrument/detector_1/position_y',
    'ccdx0': '/entry/instrument/detector_1/beam_center_position_x',
    'ccdy0': '/entry/instrument/detector_1/beam_center_position_y',
    'pix_dim_x': '/entry/instrument/detector_1/x_pixel_size',
    'pix_dim_y': '/entry/instrument/detector_1/x_pixel_size',
    'y_pixel_size': '/entry/instrument/detector_1/y_pixel_size',
    'bcx': '/entry/instrument/detector_1/beam_center_x',
    'bcy': '/entry/instrument/detector_1/beam_center_y',
    'det_dist': '/entry/instrument/detector_1/distance',
    }
}
